{{- if .Values.clusterVPA.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "castai-agent.fullname" . }}-cpvpa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "castai-agent.fullname" . }}-cpvpa
    app.kubernetes.io/instance: {{ include "castai-agent.fullname" . }}-cpvpa
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-agent.annotations" . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "castai-agent.fullname" . }}-cpvpa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "castai-agent.fullname" . }}-cpvpa
        app.kubernetes.io/instance: {{ include "castai-agent.fullname" . }}-cpvpa
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.priorityClass.enabled }}
      priorityClassName: {{ .Values.priorityClass.name }}
      {{- end }}
      serviceAccountName: {{ include "castai-agent.serviceAccountName" . }}
      automountServiceAccountToken: true
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: autoscaler
          image: k8s.gcr.io/cpa/cpvpa:{{ .Values.clusterVPA.version }}
          command:
            - /cpvpa
            - --target=deployment/{{ include "castai-agent.fullname" . }}
            - --namespace={{ .Values.namespace }}
            - --logtostderr=true
            - --poll-period-seconds={{ .Values.clusterVPA.pollPeriodSeconds }}
            - --config-file=/etc/config/castai-agent-autoscaler
          volumeMounts:
            - mountPath: /etc/config
              name: autoscaler-config
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      volumes:
        - name: autoscaler-config
          configMap:
            name: {{ include "castai-agent.fullname" . }}-autoscaler
{{- end }}
