{{- if .Values.clusterVPA.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: castai-agent-cvpa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: castai-agent-cvpa
    app.kubernetes.io/instance: castai-agent-cvpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: castai-agent-cvpa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: castai-agent-cvpa
        app.kubernetes.io/instance: castai-agent-cvpa
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.priorityClass.enabled }}
      priorityClassName: {{ .Values.priorityClass.name }}
      {{- end }}
      serviceAccountName: {{ include "castai-agent.serviceAccountName" . }}
      automountServiceAccountToken: true
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: autoscaler
          image: k8s.gcr.io/cpvpa-amd64:{{ .Values.cpvpa.version }}
          command:
            - /cpvpa
            - --target=deployment/{{ include "castai-agent.fullname" . }}
            - --namespace={{ .Values.namespace }}
            - --logtostderr=true
            - --poll-period-seconds={{ .Values.cpvpa.pollPeriodSeconds }}
            - --config-file=/etc/config/castai-agent-autoscaler
          volumeMounts:
            - mountPath: /etc/config
              name: autoscaler-config
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: autoscaler-config
          configMap:
            name: {{ include "castai-agent.fullname" . }}-autoscaler
{{- end }}
