apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "castai-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-agent.annotations" . | nindent 4 }}
  {{- end }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "castai-agent.selectorLabels" . | nindent 6 }}
