{{- if .Values.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "castai-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "castai-agent.serviceAccountName" . }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-agent.annotations" . | nindent 4 }}
  {{- end }}
rules:
  # ---
  # Required for cost savings estimation features.
  # ---
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - replicationcontrollers
      - persistentvolumeclaims
      - persistentvolumes
      - services
      - namespaces
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - storageclasses
      - csinodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "autoscaling"
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - watch
      - update
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - pods
    verbs:
      - get
      - list
  - nonResourceURLs:
      - "/version"
    verbs:
      - "get"
  {{- if eq .Values.provider "openshift" }}
  # ---
  # Required for OpenShift clusters to retrieve cluster version and cluster ID.
  # ---
  - apiGroups:
      - "config.openshift.io"
    resources:
      - "clusterversions"
    resourceNames:
      - "version"
    verbs:
      - get
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "castai-agent.serviceAccountName" . }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-agent.annotations" . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "castai-agent.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "castai-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{- if .Values.clusterVPA.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "castai-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-agent.annotations" . | nindent 4 }}
  {{- end }}
rules:
  # ---
  # Required for proportional vertical cluster autoscaler to adjust castai-agent requests/limits.
  # ---
  - apiGroups:
      - "apps"
    resources:
      - deployments
    resourceNames:
      - {{ include "castai-agent.fullname" . }}
    verbs:
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "castai-agent.serviceAccountName" . }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-agent.annotations" . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "castai-agent.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "castai-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- if eq .Values.provider "openshift" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "castai-agent.serviceAccountName" . }}
  namespace: openshift-machine-api
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-agent.annotations" . | nindent 4 }}
  {{- end }}
rules:
  # ---
  # Required for OpenShift clusters to retrieve cloud provider information about the Nodes: instance types, spot information, etc.
  # ---
  - apiGroups:
      - "machine.openshift.io"
    resources:
      - machines
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "castai-agent.serviceAccountName" . }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  namespace: openshift-machine-api
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-agent.annotations" . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "castai-agent.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "castai-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end}}

{{- end }}
