{{- if .Values.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "castai-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
data:
  API_KEY: {{ .Values.apiKey | b64enc | quote }}
  {{- range $k, $v := .Values.additionalSecretEnv }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
{{- end }}
