# used for testing external secret
{{- if .Values.isTest }}
---
apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
data:
  API_KEY: {{ "test" | b64enc | quote }}
{{- end }}
