apiKey: "test"
apiURL: "test"
createNamespace: true
namespace: test
clusterVPA:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 1000m
    memory: 256Mi

apiTelemetryURL: "test"
clusterID: "test"
