apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: castai-cluster-controller
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdbMinAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: castai-cluster-controller
