{{- if gt (.Values.replicas | int) 1}}
{{- if and (.Capabilities.APIVersions.Has "policy/v1") (semverCompare ">= 1.21-0" .Capabilities.KubeVersion.Version) -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: castai-cluster-controller
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdbMinAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: castai-cluster-controller
{{- end}}
