{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: castai-cluster-controller
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: castai-cluster-controller
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
rules:
  # Readonly.
  - apiGroups: [ "" ]
    resources: [ "pods", "nodes" ]
    verbs: [ "get", "list" ]
  # For node draining and patching.
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "patch", "update" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods/eviction" ]
    verbs: [ "create" ]
  # For node deletion.
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "delete" ]
  # For csr approval.
  - apiGroups: [ "certificates.k8s.io" ]
    resources: [ "certificatesigningrequests" ]
    verbs: [ "get", "list", "delete", "create" ]
  - apiGroups: [ "certificates.k8s.io" ]
    resources: [ "certificatesigningrequests/approval" ]
    verbs: [ "patch", "update" ]
  - apiGroups: [ "certificates.k8s.io" ]
    resources: [ "signers" ]
    resourceNames: [ "kubernetes.io/kubelet-serving", "kubernetes.io/kube-apiserver-client-kubelet" ]
    verbs: [ "approve" ]
  # For creating events.
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "list", "create", "patch" ]
  # For installing/updating CAST AI components.
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "clusterroles", "clusterrolebindings" ]
    resourceNames: [ "castai-cluster-controller" ]
    verbs: [ "get", "patch", "update", "delete", "escalate" ]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: castai-cluster-controller
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
rules:
  # All these rules are used for updating CAST AI namespace components via auto updates.
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "create", "update", "delete", "patch" ]
  - apiGroups: [""]
    resources: [ "serviceaccounts", "secrets", "configmaps" ]
    verbs: [ "get", "list", "create", "update", "delete", "patch" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles" ]
    verbs: [ "get", "list", "create", "update", "delete", "patch" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "rolebindings" ]
    verbs: [ "get", "list", "patch", "update", "delete" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: castai-cluster-controller
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: castai-cluster-controller
subjects:
  - kind: ServiceAccount
    name: castai-cluster-controller
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: castai-cluster-controller
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: castai-cluster-controller
subjects:
  - kind: ServiceAccount
    name: castai-cluster-controller
    namespace: {{ .Values.namespace }}
{{- end }}
