{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- include "castai-agent.annotations" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: castai-cluster-controller
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-agent.annotations" . | nindent 4 }}
  {{- end }}
rules:
  # Readonly.
  - apiGroups: [ "" ]
    resources: [ "pods", "nodes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get" ]
  # For node draining and patching.
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "patch", "update" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods/eviction" ]
    verbs: [ "create" ]
  # For node deletion.
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "delete" ]
  # For csr approval.
  - apiGroups: [ "certificates.k8s.io" ]
    resources: [ "certificatesigningrequests" ]
    verbs: [ "get", "list", "delete", "create", "watch" ]
  - apiGroups: [ "certificates.k8s.io" ]
    resources: [ "certificatesigningrequests/approval" ]
    verbs: [ "patch", "update" ]
  - apiGroups: [ "certificates.k8s.io" ]
    resources: [ "signers" ]
    resourceNames: [ "kubernetes.io/kubelet-serving", "kubernetes.io/kube-apiserver-client-kubelet" ]
    verbs: [ "approve" ]
  # For creating events.
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "list", "create", "patch" ]
  # For installing/updating CAST AI components.
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles", "clusterroles", "clusterrolebindings" ]
    resourceNames: [ "castai-cluster-controller", "castai-evictor", "castai-agent", "castai-spot-handler", "castai-sec-agent" ]
    verbs: [ "get", "patch", "update", "delete", "escalate" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    resourceNames: [ "castai-agent" ]
    verbs: [ "delete" ]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: castai-cluster-controller
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-agent.annotations" . | nindent 4 }}
  {{- end }}
rules:
  # Controller has full access in castai-agent namespace. This is required to fully manage castai components.
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "*" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: castai-cluster-controller
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-agent.annotations" . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: castai-cluster-controller
subjects:
  - kind: ServiceAccount
    name: castai-cluster-controller
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: castai-cluster-controller
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-agent.annotations" . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: castai-cluster-controller
subjects:
  - kind: ServiceAccount
    name: castai-cluster-controller
    namespace: {{ .Release.Namespace }}
{{- end }}
