apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "pod-mutator.webhookName" . }}
  labels:
  {{- include "pod-mutator.labels" . | nindent 4 }}
webhooks:
  - name: pod-mutator.cast.ai
    failurePolicy: {{ .Values.webhook.failurePolicy | default "Ignore"}}
    sideEffects: None
    timeoutSeconds: 1
    reinvocationPolicy: {{ .Values.webhook.reinvocationPolicy | default "Never"}}
    objectSelector:
      matchExpressions:
        # Exclude self.
        {{- include "pod-mutator.exludeSelfLabelSelectors" . | nindent 8 }}
        - key: pod-mutator.cast.ai/ignore
          operator: NotIn
          values:
            - "true"
    namespaceSelector:
      matchExpressions:
        - key: pod-mutator.cast.ai/ignore
          operator: NotIn
          values:
            - "true"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
    admissionReviewVersions:
      - v1
    clientConfig:
      {{- if .Values.webhook.url }}
      url: "{{ .Values.webhook.url }}/v1/mutate"
      {{- else }}
      service:
        name: {{ include "pod-mutator.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /v1/mutate
  {{- end }}

