apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "castai-cloud-proxy.fullname" . }}
  labels:
    {{- include "castai-cloud-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "castai-cloud-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "castai-cloud-proxy.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "castai-cloud-proxy.serviceAccountName" . }}
      {{- if .Values.priorityClass.enabled }}
      priorityClassName: {{ .Values.priorityClass.name }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: healthz
              containerPort: 9091
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe: {{- .Values.livenessProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          readinessProbe: {{- .Values.readinessProbe | toYaml | nindent 12 }}
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CAST_URL
              value: {{ required "castai.apiURL must be provided" .Values.castai.apiURL | quote }}
            - name: CAST_GRPC_URL
              value: {{ required "castai.grpcURL must be provided" .Values.castai.grpcURL | quote }}
            - name: CLUSTER_ID
              value: {{ required "castai.clusterID must be provided" .Values.castai.clusterID | quote }}
            {{- if .Values.gke.auth.jsonCredentials }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/opt/google/google-credentials.json"
            {{- end }}
            {{- range $name, $value := .Values.additionalEnv }}
            - name: "{{ $name }}"
              value: "{{ $value }}"
            {{- end }}
            - name: USE_COMPRESSION
              value: {{ .Values.castai.useCompression | quote }}
          envFrom:
            - secretRef:
          {{- if .Values.castai.apiKey }}
                name: {{ include "castai-cloud-proxy.fullname" . -}}
          {{- else }}
                name: {{ required "castai.apiKey or castai.apiKeySecretRef must be provided" .Values.castai.apiKeySecretRef -}}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.gke.auth.jsonCredentials }}
          - name: gcp-creds
            mountPath: "/opt/google"
            readOnly: true
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.gke.auth.jsonCredentials }}
        - name: gcp-creds
          secret:
            secretName: {{ include "castai-cloud-proxy.fullname" . }}-gcp-creds
      {{- end }}
