{{- if .Values.gcpConfiguration.auth.jsonCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "castai-cloud-proxy.fullname" . }}-gcp-creds
  labels:
    {{- include "castai-cloud-proxy.labels" . | nindent 4 }}
stringData:
  google-credentials.json: | {{ .Values.gcpConfiguration.auth.jsonCredentials | nindent 4 }}
{{- end }}

