apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "castai-cloud-proxy.fullname" . }}
  labels:
    {{- include "castai-cloud-proxy.labels" . | nindent 4 -}}
  {{- if gt (len .Values.global.commonAnnotations) 0 }}
  annotations:
    {{- include "castai-cloud-proxy.annotations" . | nindent 4 }}
  {{- end }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "castai-cloud-proxy.selectorLabels" . | nindent 6 }}
