{{- if .Values.priorityClass.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "castai-cloud-proxy.fullname" . }}-critical-pods
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai-cloud-proxy.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-cloud-proxy.annotations" . | nindent 4 }}
  {{- end }}
spec:
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values:
          # Required to ensure castai-cloud-proxy is always running to provide autoscaling capabilities.
          - system-cluster-critical
{{- end }}

