{{- if .Values.castai.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "castai-cloud-proxy.fullname" . }}
  labels:
    {{- include "castai-cloud-proxy.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-cloud-proxy.annotations" . | nindent 4 }}
  {{- end }}
data:
  CAST_API_KEY: {{ .Values.castai.apiKey | b64enc | quote }}
{{- end }}
