apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pod-pinner.fullname" . }}
  labels:
    {{- include "pod-pinner.labels" . | nindent 4 }}
  {{ if gt (len .Values.global.commonAnnotations) 0 -}}
  annotations:
    {{- include "pod-pinner.annotations" . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pod-pinner.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "pod-pinner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
