apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pod-pinner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pod-pinner.labels" . | nindent 4 }}
rules:
  # ---
  # Required for Webhook functionality.
  # ---
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - {{ include "pod-pinner.certsSecretName" . | quote }}
    verbs:
      - update
      - patch
      - get
      - watch
