{{- if .Values.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pod-pinner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pod-pinner.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "pod-pinner.annotations" . | nindent 4 }}
  {{- end }}
data:
  API_KEY: {{ .Values.apiKey | b64enc | quote }}
  {{- range $k, $v := .Values.additionalSecretEnv }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
{{- end }}
