apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pod-pinner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pod-pinner.labels" . | nindent 4 }}
data:
  API_KEY: {{ .Values.api.key | b64enc | quote }}
