apiVersion: v1
kind: Service
metadata:
  name: {{ include "pod-pinner.leaderServiceName" . }}
  labels:
    {{- include "pod-pinner.labels" . | nindent 4 }}
  {{ if gt (len .Values.global.commonAnnotations) 0 -}}
  annotations:
    {{- include "pod-pinner.annotations" . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
