apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "pod-pinner.webhookName" . }}
  labels:
    {{- include "pod-pinner.labels" . | nindent 4 }}
  {{ if gt (len .Values.global.commonAnnotations) 0 -}}
  annotations:
    {{- include "pod-pinner.annotations" . | nindent 4 }}
  {{- end }}
webhooks:
  {{- if gt .Values.replicaCount 0 }}
  - name: pod-pinner.cast.ai
    failurePolicy: {{ .Values.webhook.failurePolicy | default "Ignore"}}
    sideEffects: None
    timeoutSeconds: 3
    objectSelector:
      matchExpressions:
        # We don't want to match ourselves since it would cause a chicken and egg problem:
        # in order for our pod to come up, the pod would need to be already listening for requests.
        {{- include "pod-pinner.exludeSelfLabelSelectors" . | nindent 8 }}
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: "*"
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      {{- if .Values.webhook.url }}
      url: "{{ .Values.webhook.url }}/mutate"
      {{- else }}
      service:
        name: {{ include "pod-pinner.leaderServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate
        port: {{ .Values.service.port }}
      {{- end }}
  {{- end }}
