apiKey: "test"
apiURL: "test"
provider: "eks"
namespace: "default"
clusterVPA:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 1000m
    memory: 256Mi

agentActions:
  enabled: true
  apiTelemetryURL: "test"
  clusterID: "test"
