checks:
  exclude:
    - "unset-cpu-requirements"
    - "unset-memory-requirements"

  ignorePaths:
    - ./charts/egressd/**
    - ./charts/kvisor/**
    - ./charts/kvisord/**
    - ./charts/gpu-metrics-exporter/**
