# Default values for cast-cloud-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gke:
  # -- Optional: by default metadata server is used. Override this options to choose another authentication method (https://cloud.google.com/docs/authentication/application-default-credentials).
  auth:
    # -- JSON credentials to use when authenticating against GCP.
    jsonCredentials: ""
    # -- Secret to mount JSON credentials from. The credentials JSON must be provided in the `google-credentials.json` key.
    jsonCredentialsSecretRef: ""

# -- CAST AI specific settings
castai:
  # -- The CAST AI API URL.
  apiURL: "https://api.cast.ai"
  # -- The CAST AI gRPC URL.
  grpcURL: "api-grpc.cast.ai:443"
  # -- The CAST AI API key. Either this or apiKeySecretRef must be provided.
  apiKey: ""
  # -- Kubernetes Secret reference for the CAST AI API key. Either this or apiKey must be provided.
  apiKeySecretRef: ""
  # -- The CAST AI cluster ID.
  clusterID: ""

# -- Used to set additional environment variables for the cloud-proxy container.
additionalEnv:
  LOG_LEVEL: "4"
  # PPROF_PORT: "6060"

priorityClass:
  enabled: true
  name: system-cluster-critical

replicaCount: 1

image:
  repository: us-docker.pkg.dev/castai-hub/library/cloud-proxy
  pullPolicy: IfNotPresent
  tag: ""

livenessProbe:
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 1
  periodSeconds: 10
  httpGet:
    path: /livez
    port: 9091

readinessProbe:
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 1
  periodSeconds: 10
  httpGet:
    path: /readyz
    port: 9091

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

commonAnnotations: {}
podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
    - ALL

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
