# Default values for cast-cloud-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


config:
  gcpCredentials: ""
  tls:
    enabled: true

# TODO implement non-metadata server auth

gcpConfiguration:
  # -- Select the authentication mode to use to access Google Cloud APIs. Exactly one option from [metadata, raw JSON, secret reference] must be provided.
  auth:
    # -- Authenticate via node's metadata server. Requires to be running on a google cloud compute node.
    useMetadataServer: true
    # -- JSON credentials to use when authenticating against GCP.
    jsonCredentials: ""
    # -- Secret to mount JSON credentials from.
    jsonCredentialsSecretRef: ""

# -- CAST AI specific settings
castai:
  # -- The CAST AI API URL.
  apiURL: "https://api.cast.ai"
  # -- The CAST AI gRPC URL.
  grpcURL: "api-grpc.cast.ai:443"
  # -- The CAST AI API key. Either this or apiKeySecretRef must be provided.
  apiKey: ""
  # -- Kubernetes Secret reference for the CAST AI API key. Either this or apiKey must be provided.
  apiKeySecretRef: ""
  # -- The CAST AI cluster ID.
  clusterID: ""

# -- Used to set additional environment variables for the cloud-proxy container.
additionalEnv:
  LOG_LEVEL: "4"
  # PPROF_PORT: "6060"

priorityClass:
  enabled: true
  name: system-cluster-critical

replicaCount: 2

image:
  repository: us-docker.pkg.dev/castai-hub/library/cloud-proxy
  pullPolicy: IfNotPresent
  tag: ""

livenessProbe:
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 1
  periodSeconds: 10
  httpGet:
    path: /livez
    port: 9091

readinessProbe:
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 1
  periodSeconds: 10
  httpGet:
    path: /readyz
    port: 9091

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

commonAnnotations: {}
podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
    - ALL

resources:
   limits:
     cpu: 1
     memory: 512Mi
   requests:
     cpu: 100m
     memory: 128Mi

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - castai-cloud-proxy
          topologyKey: kubernetes.io/hostname
