apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ai-optimizer-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-optimizer-proxy.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - watch
