{{- if .Values.castai.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-optimizer-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-optimizer-proxy.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "ai-optimizer-proxy.annotations" . | nindent 4 }}
  {{- end }}
data:
  API_KEY: {{ .Values.castai.apiKey | b64enc | quote }}
  {{- range $k, $v := .Values.additionalSecretEnv }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
{{- end }}
