apiVersion: v1
kind: Service
metadata:
  name: headless-{{ include "name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 9050
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
