apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "annotations" . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
    - name: grpc
      port: 9050
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 2112
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
