apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
spec:
  ports:
    {{- range $index, $endpoint := .Values.endpoints}}
    - name: endpoint-{{$index}}
      port: {{$endpoint.port}}
      targetPort: {{$endpoint.port}}
      protocol: TCP
    {{- end }}
    - name: grpc
      port: 9050
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 2112
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
