apiVersion: v1
kind: ConfigMap
metadata:
  name: castai-sec-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai-sec-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl (mergeOverwrite (tpl .Values.config . | fromYaml) .Values.structuredConfig | toYaml) . | nindent 4 }}

