{{- if or .Values.apiKey .Values.castai.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: castai-sec-agent
  labels:
    {{- include "castai-sec-agent.labels" . | nindent 4 }}
data:
  {{- if .Values.apiKey }}
  API_KEY: {{ required "apiKey must be provided" .Values.apiKey | b64enc | quote }}
  {{- else }}
  API_KEY: {{ required "castai.apiKey must be provided" .Values.castai.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}
