apiVersion: v2
name: castai-sec-agent
description: CAST AI security agent deployment chart.
type: application
version: 0.15.3
appVersion: "v0.19.3"
dependencies:
  - name: tetragon
    condition: tetragon.enabled
    repository: https://helm.cilium.io
    version: 0.8.3
