# Default values for castai-audit-logs-receiver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: us-docker.pkg.dev/castai-hub/library/audit-logs-receiver
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# CAST AI API configuration.
castai:
  # Token to be used for authorizing access to the CASTAI API.
  apiKey: ""

  # Name of secret with Token to be used for authorizing access to the API.
  # apiKey and apiKeySecretRef are mutually exclusive.
  # The referenced secret must provide the token in .data["CASTAI_API_KEY"].
  apiKeySecretRef: ""

  # CASTAI public api url.
  apiURL: "https://api.cast.ai"

# Annotations to add to all resources.
commonAnnotations: {}

# Labels to add to all resources.
commonLabels: {}

# Override the name of the chart.
nameOverride: ""

# Override the release name used for the full names of resources.
fullnameOverride: ""

# Annotations to be added to pods.
podAnnotations: {}

# Labels to be added to pods.
podLabels: {}

# Pod security context.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
podSecurityContext: {}

# Container security context.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
containerSecurityContext: {}

# Resource limits & requests.
resources: {}

# Pod node selector rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
nodeSelector: {}

# Pod toleration rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# Pod affinity rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

rollout:
  rollingUpdate: {}
  strategy: RollingUpdate

configMap:
  # Specifies whether a configMap should be created.
  create: true

# Host networking requested for this pod. Use the host's network namespace.
hostNetwork: false

## Persist collector state to a persistent volume.
persistence:
  enabled: true
  # Name of an existing PersistentVolumeClaim to use.
  existingClaim: ""
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 50M
  annotations: {}

statefulset:
  podManagementPolicy: "Parallel"

## OpenTelemetry Collector configuration.
## Ref: https://opentelemetry.io/docs/collector/configuration/
config:
  receivers:
    castai-audit-logs:
      api:
        url: ${env:CASTAI_API_URL}  # Use CASTAI_API_URL env variable to override default API URL (https://api.cast.ai/).
        key: ${env:CASTAI_API_KEY}  # Use CASTAI_API_KEY env variable to provide API Access Key.
      poll_interval_sec: 10  # This parameter defines poll cycle in seconds.
      page_limit: 100  # This parameter defines the max number of records returned from the backend in one page.
      storage:
        type: "persistent"
        filename: "/var/lib/otelcol/file_storage/audit_logs_poll_data.json"

  exporters:
    logging:
      verbosity: detailed
      sampling_initial: 5
      sampling_thereafter: 200

  extensions:
    # The health_check extension is mandatory for this chart.
    # Without the health_check extension the collector will fail the readiness and liveliness probes.
    # The health_check extension can be modified, but should never be removed.
    health_check: {}

  service:
    extensions: [health_check]
    telemetry:
      logs:
        level: "debug"
    pipelines:
      logs:
        receivers: [castai-audit-logs]
        exporters: [logging]
