replicas: 2

# -- URL to the CAST AI API server.
apiURL: "api.cast.ai"

# -- Token to be used for authorizing access to the CAST AI API.
#
apiKey: ""

# -- ID of the cache group for which cache configuration should be pulled.
#
cacheGroupID: ""

resources:
  proxy:
    cpu: "500m"
    memoryRequest: "200Mi"
    memoryLimit: "200Mi"
    # -- defines how much of proxy container disk space is allocated for cache.
    ephemeralStorage: 10Gi
    # -- max allowed database size in disk.
    cacheDbSizeBytes: 10000000000
    # -- maximum number of entries to keep in the proxy.
    maxCacheEntries: 1000000000
  queryProcessor:
    cpu: "500m"
    memory: "500Mi"

proxy:
  # -- Default proxy log level.
  logLevel: "filter:info"
  # -- Ensure proxy has retrieved initial cache configuration before accepting connections.
  readinessProbeEnabled: true
  # -- Number of parallel processing streams. This needs to be balanced with cpu resoures for proxy and QP.
  concurrency: 12
  # -- DNS lookup mode when communicating to outside. will prioritize IPV4 addresses. change to V6_ONLY to use v6 addresses instead.
  dnsLookupFamily: V4_PREFERRED


queryProcessor:
  # -- Default query-processor log level.
  logLevel: "warn"


queryProcessorImage:
  repository: us-docker.pkg.dev/castai-hub/library/query-processor
  pullPolicy: IfNotPresent
  tag: ""  # uses values from _versions.tpl for default value

proxyImage:
  repository: us-docker.pkg.dev/castai-hub/library/dbo-proxy
  pullPolicy: IfNotPresent
  tag: ""  # uses values from _versions.tpl for default value

# -- Pod toleration rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: {}

# -- Pod node selector rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
nodeSelector: {}

# -- Pod affinity rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                # this will get replaced with actual app name
                - APP_NAME
        topologyKey: kubernetes.io/hostname

  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: NotIn
              values:
                - windows
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: provisioner.cast.ai/managed-by
              operator: In
              values:
                - cast.ai


