apiVersion: v2
name: castai-cluster-controller
description: Cluster controller is responsible for handling certain Kubernetes actions such as draining and deleting nodes, adding labels, approving CSR requests.
type: application
version: 0.53.4
appVersion: "v0.37.5"
