# Default values for castai-cluster-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 2
pdbMinAvailable: 1
leaderElectionEnabled: true

# labels to add to all resources
commonLabels: {}

# annotations to add to all resources
commonAnnotations: {}

nameOverride: ""
fullnameOverride: castai-cluster-controller

# By default namespace is expected to be created by castai-agent.
createNamespace: false

image:
  repository: us-docker.pkg.dev/castai-hub/library/cluster-controller
  # Tag is set using Chart.yaml appVersion field.
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: {}

# Controls `deployment.spec.strategy` field
updateStrategy:
  type: Recreate

# CAST AI API configuration.
castai:
  # Token to be used for authorizing agent access to the CASTAI API
  apiKey: ""

  # Name of secret with Token to be used for authorizing agent access to the API
  # apiKey and apiKeySecretRef are mutually exclusive
  # The referenced secret must provide the token in .data["API_KEY"]
  apiKeySecretRef: ""

  # CASTAI public api url.
  apiURL: "https://api.cast.ai"

  # CASTAI Cluster unique identifier.
  clusterID: ""

podAnnotations: {}
podLabels: {}

additionalEnv:
  LOG_LEVEL: "5"

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    memory: 1Gi

# Pod toleration rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: {}

# Pod node selector rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
nodeSelector: {}

# Pod affinity rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: NotIn
              values:
                - windows
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - castai-cluster-controller
        topologyKey: kubernetes.io/hostname

# Pod security context.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext: {}

serviceAccount:
  create: true
  # Annotations to add to the service account.
  annotations: {}
  name: "castai-cluster-controller"

# For aks we need some extra components (daemon set to collect init data).
aks:
  enabled: false
  nodeSelector:
    provisioner.cast.ai/aks-init-data: "true"

priorityClass:
  enabled: true
  name: system-cluster-critical

# Settings for configuring k8s client used in castai-cluster-controller.
k8sApiClient:
  # Client uses token based rate limiting. By default, client has 150 api request burst limit set.
  # Buffer is refilled with 25 tokens every second. During sustained load client will be capped at 25 requests / sec.
  rateLimit:
    burst: 150
    qps: 25
