# Default values for castai-cluster-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 2
pdbMinAvailable: 1
leaderElectionEnabled: true
namespace: "castai-agent"

nameOverride: ""
fullnameOverride: castai-cluster-controller

# By default namespace is expected to be created by castai-agent.
createNamespace: false

image:
  repository: us-docker.pkg.dev/castai-hub/library/cluster-controller
  # Tag is set using Chart.yaml appVersion field.
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: {}

# Controls `deployment.spec.strategy` field
updateStrategy:
  type: Recreate

castai:
  # Token to be used for authorizing agent access to the CASTAI API
  apiKey: ""

  # CASTAI public api url.
  apiURL: "https://api.cast.ai"

  # CASTAI Cluster unique identifier.
  clusterID: ""

podAnnotations: {}
podLabels: {}

additionalEnv:
  LOG_LEVEL: "5"

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    memory: 1Gi

# Pod toleration rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: {}

# Pod node selector rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
nodeSelector: {}

# Pod affinity rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: NotIn
              values:
                - windows
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - castai-cluster-controller
          topologyKey: kubernetes.io/hostname

securityContext: {}

serviceAccount:
  create: true
  # Annotations to add to the service account.
  annotations: {}

aks:
  enabled: false
  nodeSelector:
    provisioner.cast.ai/aks-init-data: "true"

priorityClass:
  enabled: false
  name: system-cluster-critical
