apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pod-pinner-ext.fullname" . }}
  labels:
    {{- include "pod-pinner-ext.labels" . | nindent 4 }}
  {{ if gt (len .Values.global.commonAnnotations) 0 -}}
  annotations:
    {{- include "pod-pinner-ext.annotations" . | nindent 4 }}
  {{- end }}
rules:
  # ---
  # Required to execute pod pinning actions.
  # ---
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/binding
    verbs:
      - create
  # ---
  # Required for Webhook functionality.
  # ---
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    resourceNames:
      - {{ include "pod-pinner-ext.webhookName" . | quote }}
    verbs:
      - watch
      - get
      - patch
      - update
