apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pod-pinner-ext.fullname" . }}
  labels:
    {{- include "pod-pinner-ext.labels" . | nindent 4 }}
  {{ if gt (len .Values.global.commonAnnotations) 0 -}}
  annotations:
    {{- include "pod-pinner-ext.annotations" . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pod-pinner-ext.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pod-pinner-ext.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
