collector:
  hostPID: true
  hostNetwork: true # On github actions we need host network to access kind host conntrack entries.

  image:
    repository: egressd

  extraArgs:
    log-level: debug

  containerSecurityContext:
    readOnlyRootFilesystem: false

exporter:
  image:
    repository: egressd-exporter

  extraArgs:
    log-level: debug

  containerSecurityContext:
    readOnlyRootFilesystem: false

  config: |
    exportInterval: 10s
    sinks:
      tilt_prom:
        prom_remote_write:
          url: "http://victoria-metrics-single-server:8428/api/v1/write"

castai:
  apiKey: "test"
