# CAST AI API configuration.
castai:
  # Token to be used for authorizing agent access to the CASTAI API
  apiKey: ""

  # CASTAI public api url.
  apiURL: "https://api.cast.ai"

  # CASTAI Cluster unique identifier.
  clusterID: ""

# Tetragon tracing policies
tracingPolicies:
  tcpConnections:
    enabled: true

# Tetragon chart configuration.
tetragon:
# Enable grafana phlare. Pprof endpoints should also be enabled, see extraArgs example.
#  podAnnotations:
#    phlare.grafana.com/scrape: "true"
#    phlare.grafana.com/port: "6060"
  dnsPolicy: "ClusterFirstWithHostNet"
  daemonSetAnnotations:
    kube-linter.io/ignore-all: "This component is managed by CAST AI"
  tolerations:
    - operator: Exists
  tetragon:
    image:
      repository: quay.io/cilium/tetragon-ci
      tag: b6f3056a3f6cf05e366a3e07348f7c0b6265a60f
    exportAllowList: |-
      {"event_set":["PROCESS_EXEC", "PROCESS_KPROBE"]}
    fieldFilters: |
     {"event_set": ["PROCESS_EXEC", "PROCESS_KPROBE"], "fields": "process.arguments,parent.arguments", "action": "EXCLUDE"}
    extraArgs:
      log-level: "info"
      # Enable pprof endpoints.
      # pprof-addr: ":6060"

    exportFilename: tetragon.log
    resources:
      requests:
        cpu: 20m
        memory: 128Mi
      limits:
        memory: 1Gi
  exportDirectory: "/var/run/cilium/tetragon"
  enableProcessCred: false
  enableProcessNs: false
  # TODO: fieldFilters is not available since latest chart is not released. Will need to fork chart.
  export:
    stdout:
      enabledCommand: true
      enabledArgs: true
      commandOverride: ["vector"]
      argsOverride: ["--config", "/vector/vector.yaml"]
      extraVolumeMounts:
        - name: vector-config
          mountPath: /vector
          readOnly: true
      image:
        override: timberio/vector:0.25.1-alpine
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 128Mi
  extraVolumes:
    - name: vector-config
      configMap:
        name: castai-tetragon-vector-config
        items:
          - key: "vector.yaml"
            path: "vector.yaml"

# Vector chart configuration for Tetragon logs export.
vector:
  role: Aggregator
  terminationGracePeriodSeconds: 30
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1010
  env:
    - name: CASTAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: castai-tetragon
          key: API_KEY
          optional: true
  existingConfigMaps:
    - castai-vector-aggregator-config
  dataDir: "/vector-data-dir"
  service:
    ports:
      - name: vector
        port: 6000
        protocol: TCP
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      memory: 512Mi

vectorAggregator:
  logToStdout: false
