apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.resumeCronJobName }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.resumeCronSchedule }}"
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  {{- if and .Values.timeZone (semverCompare ">=1.25-0" .Capabilities.KubeVersion.GitVersion) }}
  timeZone: {{ .Values.timeZone }}
  {{- end }}
  jobTemplate:
     spec:
      template:
        metadata:
          annotations:
            autoscaling.cast.ai/removal-disabled: "true"
        spec:
          securityContext: {{ .Values.podSecurityContext | toYaml | nindent 12 }}
          priorityClassName: system-cluster-critical
          tolerations:
          - key: "scheduling.cast.ai/paused-cluster"
            operator: Exists
          serviceAccountName: {{ .Values.serviceAccountName }}
          containers:
          - name: pauser
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            envFrom:
              - secretRef:
                  {{- if .Values.apiKeySecretRef }}
                  name: {{ .Values.apiKeySecretRef }}
                  {{- else }}
                  name: {{ .Values.secretName }}
                  {{- end }}
                  optional: false
            securityContext:
              readOnlyRootFilesystem: true   
            env:
              - name: CLOUD
                value: "{{ .Values.cloud }}"
              - name: ACTION
                value: "resume"
              - name: CLUSTER_ID
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Values.configMapName }}
                    key: CLUSTER_ID
              - name: API_URL
                value: {{ .Values.apiUrl }}
          restartPolicy: {{ .Values.restartPolicy }}
      backoffLimit: {{ .Values.backoffLimit }}
