apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "name" . }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "name" . }}
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "name" . }}
    spec:
      securityContext:
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 60
      volumes:
        - name: envoy-config
          configMap:
            name: {{ include "name" . }}-envoy-config
      containers:
        - name: query-processor
          image: "{{ .Values.qpImage }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 9050
              protocol: TCP
            - name: postgres
              containerPort: 5432
              protocol: TCP
            - name: metrics
              containerPort: 2112
              protocol: TCP
          env:
            - name: API_URL
              value: {{ required "apiURL must be provided" .Values.apiURL | printf "https://%s" }}
            - name: API_KEY
              value: {{ .Values.apiKey | quote }}
            - name: PROXY_METRICS_PORT
              value: "9901"
            - name: INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CONTAINER_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_SERVICE_NAME
              value: {{ include "name" . }}
            - name: SERVER_PORT
              value: "9050"
            - name: METRICS_PORT
              value: "2112"
            - name: PEERS_URL
              value: {{ include "name" . }}
            - name: CACHE_GROUP_ID
              value: {{ .Values.cacheGroupID | required ".Values.cacheGroupID is required." | quote }}
            - name: OWN_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          readinessProbe:
            grpc:
              port: 9050
            initialDelaySeconds: 0
          resources:
            requests:
              cpu: {{ .Values.resources.queryProcessor.cpu }}
            limits:
              memory: {{ .Values.resources.queryProcessor.memory }}
        - name: proxy
          image: {{ .Values.proxyImage }}
          imagePullPolicy: IfNotPresent
          command:
            - /home/polyscale/envoy
          args:
            - -c
            - /home/polyscale/envoy.yaml
            - --component-log-level
            - {{ .Values.proxy.logLevel }}
            - --file-flush-interval-msec
            - "25000"
            - --enable-core-dump

          ports:
            - name: grpc
              containerPort: 9050
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.proxy.cpu }}
              ephemeral-storage: {{ .Values.resources.proxy.ephemeralStorage }}
            limits:
              memory: {{ .Values.resources.proxy.memory }}
          volumeMounts:
            - name: envoy-config
              mountPath: /home/polyscale/envoy.yaml
              subPath: envoy-config.yaml
