cacheGroupID: "123"
apiKey: "456"

upstreamPostgresHostname: random.hostname

resources:
  proxy:
    ephemeralStorage: 5Mi

proxy:
  readinessProbeEnabled: true

podLabels:
  podLabel: label

podAnnotations:
  podAnnotation: annotation


commonLabels:
  commonLabel: label

commonAnnotations:
  commonAnnotation: annotation
