cacheGroupID: "123"
apiKey: "456"

resources:
  proxy:
    ephemeralStorage: 5Mi

proxy:
  readinessProbeEnabled: false

podLabels:
  podLabel: label

podAnnotations:
  podAnnotation: annotation


commonLabels:
  commonLabel: label

commonAnnotations:
  commonAnnotation: annotation
