---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "evictor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "evictor.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "evictor.annotations" . | nindent 4 }}
  {{- end }}
rules:
  # ------------------------------------------------
  # Leader election
  # ------------------------------------------------
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - watch
      - update
  {{- if .Values.clusterVPA.enabled }}
  # ---
  # Required for proportional vertical cluster autoscaler to adjust evictor requests/limits.
  # ---
  - apiGroups:
      - "apps"
    resources:
      - deployments
    resourceNames:
      - {{ include "evictor.fullname" . }}
    verbs:
      - patch
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "evictor.serviceAccountName" . }}
  labels:
    {{- include "evictor.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "evictor.annotations" . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "evictor.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "evictor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
