{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "evictor.serviceAccountName" . }}
  labels:
    {{- include "evictor.labels" . | nindent 4 }}
rules:
  # ------------------------------------------------
  # Leader election
  # ------------------------------------------------
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
{{- end }}
