{{- if .Values.trustedCACert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evictor.fullname" . }}-tls-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "evictor.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "evictor.annotations" . | nindent 4 }}
  {{- end }}
data:
  TLS_CA_CERT_FILE: {{ .Values.trustedCACert | b64enc | quote }}
{{- end }}
