apiVersion: v2
name: castai-hosted-model
description: CAST AI hosted model deployment chart. Currently, it's just a pass through to ollama chart helm.
type: application
version: 0.0.3
appVersion: "v0.0.1"
dependencies:
  - name: ollama
    version: 1.4.0
    repository: https://otwld.github.io/ollama-helm/
    condition: ollama.enabled
