# Default values for castai-spot-handler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "castai-agent"

image:
  repository: us-docker.pkg.dev/castai-hub/library/spot-handler
  # Tag is set using Chart.yaml appVersion field.
  tag: ""
  pullPolicy: IfNotPresent

castai:
  # CASTAI public api url.
  apiURL: "https://api.cast.ai"

  # CASTAI Cluster unique identifier.
  clusterID: ""

  # Cloud provider (azure, gcp, aws)
  provider: ""

podAnnotations: {}
additionalEnv:
  LOG_LEVEL: "5"
  POLL_INTERVAL_SECONDS: "3"

useHostNetwork: true

resources: {}

serviceAccount:
  # Annotations to add to the service account.
  annotations: {}

nodeSelector:
  scheduling.cast.ai/spot: "true"
