namespace: default
clusterVPA:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 1000m
    memory: 256Mi

podLabels:
  team: security
  provider: alibaba

castai:
  clusterID: "test"
  apiKey: "test"
  apiURL: "test"

tolerations:
  - key: scheduling.cast.ai/spot
    operator: Exists

features:
  kubelinter:
    enabled: true
  kubebench:
    enabled: false
  imagescan:
    enabled: false
