apiVersion: v2
name: castai-pod-node-lifecycle
description: CAST AI spotonly K8s webhook to control workload placement during cluster migration and spotonly.
type: application
version: 0.19.0
appVersion: "v0.16.0"
