apiVersion: v2
name: castai-pod-node-lifecycle
description: CAST AI spot-only K8s webhook to control workload placement during cluster migration and spot-only.
type: application
version: 0.30.0
appVersion: "v0.23.0"
