namespace: default
clusterVPA:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 1000m
    memory: 256Mi

castai:
  clusterID: "test"
  apiKey: "test"
  apiURL: "test"
