namespace: default
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 1000m
    memory: 256Mi

podLabels:
  team: core
  provider: alibaba

castai:
  clusterID: "test"
  apiKey: "test"
  apiURL: "test"

tolerations:
  - key: scheduling.cast.ai/spot
    operator: Exists

clusterVPA:
  enabled: true
  version: v0.8.4
  pollPeriodSeconds: 300
