# Default values for castai-hibernate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# CAST AI API Key configuration.
# API token with Full Access permissions and encode base64
apiKey: ""

# Set CronJobs "Cloud" env variable to [EKS|GKE|AKS]
cloud: ""

# hibernate-pause cronjob schedule.
pauseCronJobName: hibernate-pause
pauseCronSchedule: "0 22 * * 1-5"

# hibernate-esume cronjob schedule.
resumeCronJobName: hibernate-resume
resumeCronSchedule: "0 7 * * 1-5"

# By default namespace is expected to be created by castai-agent.
namespace: castai-agent
agentNamespace: castai-agent

# hibernate cronjob global configurations.
secretName: castai-hibernate

serviceAccountName: hibernate

roleName: hibernate

roleBindingName: hibernate

clusterRoleName: hibernate

clusterRoleBindingName: hibernate

clusterRoleBindingAdminName: hibernate-admin

concurrencyPolicy: "Forbid"

image:
  repository: castai/hibernate
  tag: latest
  pullPolicy: Always

namespacesToKeep: ""
protectRemovalDisabled: "false"
configMapName: castai-cluster-controller

restartPolicy: "OnFailure"
backoffLimit: 0


#Override default hibernate-node size
#Set the HIBERNATE_NODE environment variable to override the default node sizing selections. 
#Make sure the size selected is appropriate for your cloud.
hibernateNode: ""



