apiVersion: v2
name: castai-pod-pinner-ext
description: |
  Library chart the the CAST AI Pod Pinner that includes additional resources such as ClusterRoles that the CAST AI auto-upgrade feature doesn't have permissions to create.
type: application
version: 1.0.0
appVersion: "v1.0.0"
