api:
  url: "https://api.cast.ai"
  grpcUrl: "grpc.cast.ai:443"
  key: ""
  clusterId: "28a491f5-1ea0-4a92-ba46-54f57c7d0aeb"

apiKeySecretRef: "test"

provider: "eks"
namespace: "default"
createNamespace: false
additionalEnv:
  EKS_ACCOUNT_ID: test
  EKS_REGION: test
  EKS_CLUSTER_NAME: test
additionalSecretEnv:
  AWS_ACCESS_KEY_ID: "key"
  AWS_SECRET_ACCESS_KEY: "secret"
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 1000m
    memory: 256Mi
isTest: true
