{{- if .Values.castai.clusterID -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduling-policies-controller
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "scheduling-policies-controller.labels" . | nindent 4 }}
  {{ if .Values.commonAnnotations -}}
  annotations:
    {{- include "scheduling-policies-controller.annotations" . | nindent 4 }}
  {{- end }}
data:
  API_URL: {{ required "castai.apiUrl must be provided" .Values.castai.apiUrl | quote }}
  CLUSTER_ID: {{ required "clusterID must be provided" .Values.castai.clusterID | quote }}
{{- end }}