apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "scheduling-policies-controller.webhookName" . }}
  labels:
  {{- include "scheduling-policies-controller.labels" . | nindent 4 }}
webhooks:
  - name: scheduling-policies-controller.cast.ai
    failurePolicy: {{ .Values.webhook.failurePolicy | default "Ignore"}}
    sideEffects: None
    timeoutSeconds: 1
    reinvocationPolicy: {{ .Values.webhook.reinvocationPolicy | default "Never"}}
    objectSelector:
      matchExpressions:
        # Exclude self.
        {{- include "scheduling-policies-controller.exludeSelfLabelSelectors" . | nindent 8 }}
        - key: scheduling-policies-controller.cast.ai/ignore
          operator: NotIn
          values:
            - "true"
    namespaceSelector:
      matchExpressions:
        - key: scheduling-policies-controller.cast.ai/ignore
          operator: NotIn
          values:
            - "true"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
    admissionReviewVersions:
      - v1
    clientConfig:
      {{- if .Values.webhook.url }}
      url: "{{ .Values.webhook.url }}/v1/mutate"
      {{- else }}
      service:
        name: {{ include "scheduling-policies-controller.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /v1/mutate
  {{- end }}

