apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "scheduling-policies-controller.fullname" . }}
  labels:
  {{- include "scheduling-policies-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - {{ include "scheduling-policies-controller.fullname" . }}-certs
    verbs:
      - get
      - update
      - patch
