apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "scheduling-policies-controller.fullname" . }}
  labels:
    {{- include "scheduling-policies-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "scheduling-policies-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "scheduling-policies-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
