{{- if .Values.castai.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: scheduling-policies-controller
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "scheduling-policies-controller.labels" . | nindent 4 }}
  {{ if .Values.commonAnnotations -}}
  annotations:
    {{- include "scheduling-policies-controller.annotations" . | nindent 4 }}
  {{- end }}
data:
  API_KEY: {{ required "apiKey must be provided" .Values.castai.apiKey | b64enc | quote }}
{{- end }}