apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scheduling-policies-controller.serviceAccountName" . }}
  labels:
  {{- include "scheduling-policies-controller.labels" . | nindent 4 }}
