{{- if .Values.isTest }}
# used for testing external secret
apiVersion: v1
kind: Secret
metadata:
  name: test
  labels:
    {{- include "scheduling-policies-controller.labels" . | nindent 4 }}
  {{ if gt (len .Values.global.commonAnnotations) 0 -}}
  annotations:
    {{- include "scheduling-policies-controller.annotations" . | nindent 4 }}
  {{- end }}
data:
  API_KEY: {{ "test" | b64enc | quote }}
{{- end }}
