{{- if and (ge .Capabilities.KubeVersion.Minor "21") (gt (int .Values.replicaCount) 1)}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pod-node-lifecycle.fullname" . }}
spec:
  minAvailable: {{ sub .Values.replicaCount 1 }}
  selector:
    matchLabels:
      {{- include "pod-node-lifecycle.selectorLabels" . | nindent 6 }}
{{- end}}
