{{- if and (ge .Capabilities.KubeVersion.Minor "21") (gt (int .Values.replicaCount) 1)}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pod-node-lifecycle.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pod-node-lifecycle.fullname" . }}
{{- end}}
