{{- if .Values.priorityClass.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "pod-node-lifecycle.fullname" . }}-critical-pods
  labels:
    {{- include "pod-node-lifecycle.labels" . | nindent 4 }}
spec:
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values:
          # Required to ensure the webhook is always running to provide autoscaling capabilities.
          - {{ .Values.priorityClass.name }}
{{- end }}
