apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pod-node-lifecycle.fullname" . }}
  labels:
  {{- include "pod-node-lifecycle.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - {{ include "pod-node-lifecycle.certsSecretName" . }}
    verbs:
      - get
      - update
      - patch
