apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: castai-pod-node-lifecycle
  labels:
    {{- include "pod-node-lifecycle.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pod-node-lifecycle.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "pod-node-lifecycle.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
