{{- if .Values.telemetry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pod-node-lifecycle.fullname" . }}-api
  labels:
  {{- include "pod-node-lifecycle.labels" . | nindent 4 }}
data:
  API_KEY: {{ required "api.key must be provided" .Values.api.key | b64enc }}
{{- end }}
