apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: castai-spot-handler
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  annotations:
    ignore-check.kube-linter.io/host-network: "Spot handler need host network to access instance metadata endpoints for spot interrupts checks."
spec:
  selector:
    matchLabels:
      name: spot-handler
  template:
    metadata:
      labels:
        name: spot-handler
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.useHostNetwork }}
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: spot-handler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: API_URL
              value: {{ required "castai.apiURL must be provided" .Values.castai.apiURL | quote }}
            - name: CLUSTER_ID
              value: {{ required "castai.clusterID must be provided" .Values.castai.clusterID | quote }}
            - name: PROVIDER
              value: {{ required "castai.provider must be provided" .Values.castai.provider | quote }}
            {{- range $k, $v := .Values.additionalEnv }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          envFrom:
            - secretRef:
                {{- if .Values.apiKeySecretRef }}
                name: {{ .Values.apiKeySecretRef }}
                {{- else }}
                # Re-use shared secret from cluster-controller.
                name: castai-cluster-controller
                {{- end }}
          {{- with .Values.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            readOnlyRootFilesystem: true
      terminationGracePeriodSeconds: 30
