{{- if .Values.castai.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "castai-audit-logs-receiver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai-audit-logs-receiver.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "castai-audit-logs-receiver.annotations" . | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.castai.apiKey }}
  CASTAI_API_KEY: {{ required "apiKey must be provided" .Values.castai.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}
