{{- if .Values.hfToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm.fullname" . }}-{{ now | date "02012006150405" }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
data:
  HF_TOKEN: {{ .Values.hfToken | b64enc | quote }}
{{- end }}
